
export const LOAD_SHOWS_SUCESS = 'LOAD_SHOWS_SUCESS'
export const LOAD_SHOWS_ERROR = "LOAD_SHOWS_ERROR"
export const LOADING_SHOWS = "LOADING_SHOWS"

export const LOAD_SHOW_DETAIL_SUCCESS = "LOAD_SHOW_DETAIL_SUCCESS"
export const LOAD_SHOW_DETAIL_ERROR = "LOAD_SHOW_DETAIL_ERROR"
export const CLEAN_SHOW_DATA = "CLEAN_SHOW_DATA"
export const LOADING_SHOW_DATA = "LOADING_SHOW_DATA"
export const LOAD_SHOW_CHAPTERS_SUCCESS = "LOAD_SHOW_CHAPTERS_SUCCESS"
export const LOAD_SHOW_CHAPTERS_ERROR = "LOAD_SHOW_CHAPTERS_ERROR"
export const LOADING_SHOW_CHAPTERS = "LOADING_SHOW_CHAPTERS"
export const LOAD_SHOW_CHARACTERS_SUCCESS = "LOAD_SHOW_CHARACTERS_SUCCESS"
export const LOAD_SHOW_CHARACTERS_ERROR = "LOAD_SHOW_CHARACTERS_ERROR"
export const LOADING_SHOW_CHARACTERS = "LOADING_SHOW_CHARACTERS"


