export const LOAD_SHOWS_SUCESS = 'LOAD_SHOWS_SUCESS';
export const LOAD_SHOWS_ERROR = 'LOAD_SHOWS_ERROR';
export const LOADING_SHOWS = 'LOADING_SHOWS';
export const LOAD_SEARCH_SUCCESS = 'LOAD_SEARCH_SUCCESS';
export const LOAD_SEARCH_ERROR = 'LOAD_SEARCH_ERROR';
export const LOADING_SEARCH = 'LOADING_SEARCH';
export const CLEAN_SEARCH_DATA = 'CLEAN_SEARCH_DATA';
export const FILL_SEARCH_QUERY = 'FILL_SEARCH_QUERY';

export const LOAD_SHOW_DETAIL_SUCCESS = 'LOAD_SHOW_DETAIL_SUCCESS';
export const LOAD_SHOW_DETAIL_ERROR = 'LOAD_SHOW_DETAIL_ERROR';
export const CLEAN_SHOW_DATA = 'CLEAN_SHOW_DATA';
export const LOADING_SHOW_DATA = 'LOADING_SHOW_DATA';
export const LOAD_SHOW_CHAPTERS_SUCCESS = 'LOAD_SHOW_CHAPTERS_SUCCESS';
export const LOAD_SHOW_CHAPTERS_ERROR = 'LOAD_SHOW_CHAPTERS_ERROR';
export const LOADING_SHOW_CHAPTERS = 'LOADING_SHOW_CHAPTERS';
export const LOAD_SHOW_CHARACTERS_SUCCESS = 'LOAD_SHOW_CHARACTERS_SUCCESS';
export const LOAD_SHOW_CHARACTERS_ERROR = 'LOAD_SHOW_CHARACTERS_ERROR';
export const LOADING_SHOW_CHARACTERS = 'LOADING_SHOW_CHARACTERS';
export const LOAD_SPECIFIC_CHARACTER_SUCCESS =
  'LOAD_SPECIFIC_CHARACTER_SUCCESS';
export const LOAD_SPECIFIC_CHARACTER_ERROR = 'LOAD_SPECIFIC_CHARACTER_ERROR';
export const LOADING_SPECIFIC_CHARACTER = 'LOADING_SPECIFIC_CHARACTER';
export const LOAD_SHOW_GENRES_SUCCESS = 'LOAD_SHOW_GENRES_SUCCESS';
export const LOAD_SHOW_GENRES_ERROR = 'LOAD_SHOW_GENRES_ERROR';
export const LOADING_SHOW_GENRES = 'LOADING_SHOW_GENRES';

